"""unique_event name

Revision ID: 8ee9473ef99e
Revises: 2fa12a3d5aa2
Create Date: 2025-06-18 23:18:06.838936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee9473ef99e'
down_revision: Union[str, Sequence[str], None] = '2fa12a3d5aa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events') as batch_op:
        batch_op.create_unique_constraint('uix_event_name', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_event_name', 'events', type_='unique')
    # ### end Alembic commands ###
